server:
  port: 8401

spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.102.175:8848
    sentinel:
      transport:
        dashboard: localhost:8080


management:
  endpoints:
    web:
      exposure:
        include: "*"
