server:
  port: 9004

spring:
  application:
    name: sentinel-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.102.175:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.113.102.175:3306/db2020?characterEncoding=utf-8&useSSL=false
    username: root

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.entity
