server:
  port: 9527

spring:
  application:
    name: cloud-gateway

    #配置路由的第一种方式（yml配置方式），也可以使用第二种方式（硬编码方式）-自定义GatewayConfig.java
  cloud:
    gateway:
      routes:
        - id: payment_routh   #路由名称，保持唯一即可
          uri: http://localhost:8001      #匹配后，提供服务的路由地址(写死的,无法修改)
          predicates:
            - Path=/payment/get/**      #断言，路径匹配规则
        - id: payment_routh1   #路由名称，保持唯一即可
          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配后，提供服务的路由地址(动态路由，根据服务名称，可以实现负载均衡)
          predicates:
            - Path=/payment/port      #断言，路径匹配规则
      discovery:
        locator:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
